In [17]:
import pickle
import numpy as np
import os

with open('processed_data/dataset.pkl', 'rb') as f:
    data = pickle.load(f)
    
# data is a list of tuples (csv_index, filename, labels).
# labels is a numpy array of shape (num_frames, num_actions).
# Array is multilabel, if action j is performed at frame i, then labels[i][j] = 1.

data

[(0,
  '01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam01_assault01_place09_night_winter',
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=int8)),
 (1,
  '01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam02_assault01_place09_night_winter',
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=int8)),
 (2,
  '01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam01_assault01_place09_night_summer',
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]], dtype=int8)),
 (3,
  '01.폭행(assult)\\inside_c

In [18]:
from moviepy.editor import VideoFileClip

video_path = 'processed_data/resized_480.mp4'
clip = VideoFileClip(video_path)
width, height = clip.size

print(f"Width: {width}, Height: {height}")

Width: 720, Height: 480


In [19]:
from resnet import resnet50
import torch

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

model = resnet50()
model.to(device)
model.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [20]:
ROOT_PATH = os.path.abspath("G:\내 드라이브\Project\RGBLab\ABB\Data")

DATA_PATH = []

for single_data in data:
    DATA_PATH.append(os.path.join(ROOT_PATH, single_data[1]))

In [21]:
DATA_PATH

['G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam01_assault01_place09_night_winter',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam02_assault01_place09_night_winter',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam01_assault01_place09_night_summer',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam01_assault01_place09_night_spring',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam03_assault01_place09_night_spring',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam03_assault01_place09_night_summer',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam03_assault01_place09_night_winter',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam02_assault01_place09_night_spring',
 'G:\\내 

In [22]:
# add .mp4 to the end of each path
DATA_PATH = [path + '.mp4' for path in DATA_PATH]

DATA_PATH

['G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam01_assault01_place09_night_winter.mp4',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam02_assault01_place09_night_winter.mp4',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam01_assault01_place09_night_summer.mp4',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam01_assault01_place09_night_spring.mp4',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam03_assault01_place09_night_spring.mp4',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam03_assault01_place09_night_summer.mp4',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam03_assault01_place09_night_winter.mp4',
 'G:\\내 드라이브\\Project\\RGBLab\\ABB\\Data\\01.폭행(assult)\\inside_croki_02\\24-5\\24-5_cam02_assault01_pla

In [23]:
import cv2

from tqdm import tqdm
import cv2

def resize_video(input_path, output_path, dim=(720, 480)):
    cap = cv2.VideoCapture(input_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, 30.0, dim)
    
    with tqdm(total=total_frames, desc="Resizing video") as pbar:
        while True:
            ret, frame = cap.read()
            if not ret:
                break
            resized_frame = cv2.resize(frame, dim)
            out.write(resized_frame)
            pbar.update(1)
    
    cap.release()
    out.release()


In [24]:
import av

def get_video_duration(video_path):
    container = av.open(video_path)
    duration = container.duration / av.time_base
    return duration

In [25]:
from pytorchvideo.data.encoded_video import EncodedVideo
from torchvision.transforms import Compose
from pytorchvideo.transforms import (
    ApplyTransformToKey,
    ShortSideScale,
    UniformTemporalSubsample,
    UniformCropVideo
)
from torchvision.transforms._transforms_video import (
    CenterCropVideo,
    NormalizeVideo,
)
from tqdm import tqdm
import tempfile

num_frames = 32
sampling_rate = 6
frames_per_second = 30
clip_duration = (num_frames * sampling_rate)/frames_per_second

side_size = 360
mean=[123.675, 116.28, 103.53]
std=[58.395, 57.12, 57.375]

transform =  ApplyTransformToKey(
    key="video",
    transform=Compose(
        [
            UniformTemporalSubsample(num_frames),
            NormalizeVideo(mean, std),
            ShortSideScale(
                size=side_size
            ),
        ]
    ),
)

all_outputs = {}

for video_file in tqdm(DATA_PATH, desc="Processing videos"):
    
    # 1. resizing video
    resize_video(video_file, 'temp.mp4')
    
    # 2. feature extraction
    # init EncodedVideo instance
    video = EncodedVideo.from_path("./temp.mp4")
    total_duration = get_video_duration("./temp.mp4")
    num_clips = int(np.ceil(total_duration / clip_duration))    
    
    for i in tqdm(range(num_clips), desc="Extracting features"):
        start_sec = i * clip_duration
        end_sec = start_sec + clip_duration
        
        # load clip and transform
        video_data = video.get_clip(start_sec=start_sec, end_sec=end_sec)
        video_data = transform(video_data)
        inputs = video_data["video"]
        inputs = inputs.transpose(0, 1).to(device)
        
        # run model
        with torch.no_grad():
            outputs = model(inputs)
        
        # save outputs
        all_outputs[f'{video_file}_clip_{i+1}'] = outputs.cpu().numpy()
        
# save all outputs to a numpy file
np.save('all_outputs.npy', all_outputs)

Processing videos:   0%|          | 3/1688 [10:23<97:16:52, 207.84s/it]


KeyboardInterrupt: 